### ISSUE TITLE
Code for the Play application

### ISSUE THREAD

**Issue by NiklasA1** [fagossa/play-prometheus#3]
Great work! 

Can I find the source code for the play application somewhere? I am just starting to learn Play and Scala, and I don't have any success in putting together the pieces based on the instructions in the pdf, so I must be missing something.

Running the whole thing via docker-compose works like a charm, but I can't get something similar to work in my own toy Play app.

Any help is highly appreciated.

**Comment by fagossa** [comment]
Hello,

The code is right here: https://github.com/fagossa/play-prometheus/tree/prometheus-playFramework

**Comment by NiklasA1** [comment]
Thanks :-)
